experiment:
  version: 0.3.1
  dataset: greens
  data_config:
    strategy: dataset
    dataset_path: ../data/greens/interactions_flickr_cultural_1.tsv

#  prefiltering:
#    strategy: user_average # Not applied in the paper experiments
  splitting:
    save_on_disk: True
    save_folder: ../data/greens/splitting/
    test_splitting:
      strategy: random_subsampling
      leave_n_out: 1
      folds: 1
  top_k: 5000
  evaluation:
    cutoffs: [20,10, 5]
    simple_metrics: [nDCG,ARP]
    relevance_threshold: 1
  gpu: 0
  models:
    Random:
      meta:
        verbose: True
        save_recs: True
      seed: 42
    PureSVD:
      meta:
        save_recs: True
      factors: 10
      seed: 42
    BPRMF:
      meta:
        save_recs: True
      epochs: 10
      factors: 10
      lr: 0.001
      bias_regularization: 0
      user_regularization: 0.0025
      positive_item_regularization: 0.0025
      negative_item_regularization: 0.0025
      update_negative_item_factors: True
      update_users: True
      update_items: True
      update_bias: True
    ItemKNN:
      meta:
        save_recs: True
      neighbors: 40
      similarity: cosine
      implementation: classical
      models:
    UserKNN:
      meta:
        save_recs: True
      neighbors: 40
      similarity: cosine
      implementation: classical
    MostPop:
      meta:
        save_recs: True